/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */

group = "com.adam"
version = "1.0.0"

application {
    mainClass = "com.adam.Program"
}

plugins {
    id("java")
    id("application")
}

repositories {
    mavenCentral()
}

dependencies {

}
