# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/79ec78a2-02a8-499c-87d8-b8584a16a4c4";
      fsType = "ext4";
    };

  fileSystems."/mnt/MediaDrive" =
    { device = "/dev/disk/by-uuid/90c3ce04-a5c6-4557-9c7b-8d860be31d02";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/16ca3928-40a7-495f-b19a-48debaf7e93a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
